"""
One-time script: download Inter font (Latin subset) from Google Fonts and save
as WOFF2 files in backend/assets/fonts/.

Run from backend/:
    python scripts/download_fonts.py
"""
import base64
import sys
from pathlib import Path

import httpx

FONTS_DIR = Path(__file__).parent.parent / "assets" / "fonts"

# Google Fonts CSS API — latin subset for Inter weights we use
GOOGLE_FONTS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400;500;600;700;800;900"
    "&display=swap"
    "&subset=latin"
)

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}


def main() -> None:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Fetching font CSS from Google Fonts...")

    css_resp = httpx.get(GOOGLE_FONTS_URL, headers=HEADERS, follow_redirects=True, timeout=30)
    css_resp.raise_for_status()
    css = css_resp.text

    # Parse WOFF2 URLs and weight from the CSS
    import re
    font_face_blocks = re.findall(r"@font-face\s*\{([^}]+)\}", css, re.DOTALL)
    downloaded = 0
    failed = 0
    face_rules: list[str] = []

    for block in font_face_blocks:
        # Skip non-latin subsets
        comment_match = re.search(r"/\*\s*([^*]+)\*/", block)
        subset = comment_match.group(1).strip() if comment_match else ""
        if subset and subset != "latin":
            continue

        weight_match = re.search(r"font-weight:\s*(\d+)", block)
        url_match = re.search(r"url\(([^)]+\.woff2)\)", block)
        if not weight_match or not url_match:
            continue

        weight = weight_match.group(1)
        url = url_match.group(1).strip("'\"")
        filename = f"inter-{weight}-latin.woff2"
        dest = FONTS_DIR / filename

        if dest.exists():
            print(f"  {filename} already exists, skipping")
        else:
            print(f"  Downloading Inter {weight} -> {filename}")
            try:
                r = httpx.get(url, headers=HEADERS, follow_redirects=True, timeout=30)
                r.raise_for_status()
                dest.write_bytes(r.content)
                print(f"    saved {len(r.content):,} bytes")
                downloaded += 1
            except Exception as exc:
                print(f"    FAILED: {exc}", file=sys.stderr)
                failed += 1
                continue

        # Build @font-face rule with file path (for use in generate_fonts_css)
        b64 = base64.b64encode(dest.read_bytes()).decode()
        face_rules.append(
            f"@font-face{{font-family:'Inter';font-style:normal;font-weight:{weight};"
            f"font-display:swap;"
            f"src:url('data:font/woff2;base64,{b64}') format('woff2');}}"
        )

    if not face_rules:
        print("No font faces found — check CSS output above", file=sys.stderr)
        sys.exit(1)

    # Write a Python module with the embedded CSS
    output_py = FONTS_DIR / "inter_css.py"
    css_content = "\n".join(face_rules)
    output_py.write_text(
        f'"""Auto-generated by download_fonts.py — do not edit manually."""\n'
        f"INTER_FONT_CSS: str = {repr(css_content)}\n",
        encoding="utf-8",
    )
    print(f"\nGenerated {output_py}")
    print(f"Downloaded {downloaded} fonts, {failed} failures, {len(face_rules)} @font-face rules ready.")
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
