"""add_profile_raw_to_companies

Revision ID: f85c52ab4d63
Revises: 0001
Create Date: 2026-06-03 16:42:30.176589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f85c52ab4d63'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('profile_raw', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'profile_raw')
    # ### end Alembic commands ###
