from typing import Optional
from pydantic import BaseModel, Field
from models.enums import (
    Regulation,
    ComplianceStatus,
    Priority,
    ObligationType,
)


class RegulationApplicability(BaseModel):
    regulation: Regulation
    applies: bool
    reason: str
    key_threshold: Optional[str] = None


class RegulatoryChunk(BaseModel):
    """A single retrieved regulatory article chunk from ChromaDB."""

    regulation: Regulation
    article_number: str
    title: str
    text: str
    obligation_type: ObligationType
    applicable_to: list[str] = Field(default_factory=list)
    threshold: Optional[str] = None
    source_url: Optional[str] = None


class ComplianceGap(BaseModel):
    regulation: Regulation
    article_number: str
    article_title: str
    status: ComplianceStatus
    evidence: str = Field(..., description="Explanation of WHY this status was assigned")
    deficiency_description: Optional[str] = None


class ActionItem(BaseModel):
    regulation: Regulation
    article_number: str
    action: str
    priority: Priority
    estimated_effort: str = Field(
        ..., description="e.g., '2-4 hours', '1-2 weeks', '1 FTE-month'"
    )
    deadline: Optional[str] = None
    dependencies: list[str] = Field(default_factory=list)
    gap_reference: str = Field(..., description="Points back to the ComplianceGap this resolves")


class RegulationScore(BaseModel):
    regulation: Regulation
    total_requirements: int
    compliant: int
    partially_compliant: int
    non_compliant: int
    cannot_assess: int
    score_percent: float = Field(..., ge=0, le=100)


class ComplianceReport(BaseModel):
    job_id: str
    company_name: str
    generated_at: str

    # Section 2 — profile summary
    applicable_regulations: list[RegulationApplicability]
    inferred_characteristics: list[str]
    missing_optional_fields: list[str]
    validation_warnings: list[str]

    # Section 4 — detailed analysis
    retrieved_chunks: list[RegulatoryChunk]
    gap_analysis: list[ComplianceGap]

    # Section 5 — action plan
    action_plan: list[ActionItem]

    # Section 6 — scores
    regulation_scores: list[RegulationScore]
    overall_score_percent: float = Field(..., ge=0, le=100)

    # Section 1 — executive summary (assembled last)
    executive_summary: str = Field(default="")

    # Meta
    disclaimer: str = Field(
        default=(
            "This report is generated by an AI system and does not constitute legal advice. "
            "Consult a qualified legal professional before making compliance decisions. "
            "Complio cannot guarantee completeness or accuracy of regulatory information."
        )
    )
    requires_manual_review: list[str] = Field(
        default_factory=list,
        description="Steps or sections that failed validation and need human review",
    )
