"use client";

import { Controller, UseFormReturn } from "react-hook-form";
import { BoolField } from "./bool-field";
import type { ProfileFormData } from "@/app/analyze/page";

interface Props { form: UseFormReturn<ProfileFormData> }

export function Step10Digital({ form }: Props) {
  const { control } = form;

  return (
    <div className="flex flex-col gap-5">
      <p className="text-sm text-slate-500">
        These questions cover cookie consent (TTDSG/TDDDG), anti-money laundering (GwG), and data access obligations (EU Data Act).
      </p>

      {/* TTDSG / TDDDG */}
      <div className="pt-2 pb-1">
        <p className="text-xs font-bold uppercase tracking-widest text-brand-400">Cookie Consent (TTDSG / TDDDG)</p>
      </div>

      <Controller control={control} name="has_website" render={({ field }) => (
        <BoolField
          label="Does the company operate a public-facing website or app?"
          hint="Any website accessible by users in Germany triggers TTDSG §25 obligations."
          value={field.value} onChange={field.onChange}
        />
      )} />

      <Controller control={control} name="has_cookie_banner" render={({ field }) => (
        <BoolField
          label="Is a cookie consent banner implemented (opt-in before tracking)?"
          hint="§25 TDDDG requires informed consent BEFORE setting any non-essential cookies, pixels, or fingerprinting scripts."
          value={field.value} onChange={field.onChange}
        />
      )} />

      <Controller control={control} name="has_cookie_policy" render={({ field }) => (
        <BoolField
          label="Is there a documented cookie/tracking inventory?"
          hint="A published list of all cookies and tracking technologies used, their purposes, and retention periods."
          value={field.value} onChange={field.onChange}
        />
      )} />

      {/* GwG */}
      <div className="pt-4 pb-1">
        <p className="text-xs font-bold uppercase tracking-widest text-brand-400">Anti-Money Laundering (GwG)</p>
      </div>

      <Controller control={control} name="is_aml_obligated_sector" render={({ field }) => (
        <BoolField
          label="Is the company in an AML-obligated sector?"
          hint="Financial services, crypto, real estate brokerage, legal/notarial services, tax advisory, or gambling — §2 GwG."
          value={field.value} onChange={field.onChange}
        />
      )} />

      <Controller control={control} name="has_aml_risk_analysis" render={({ field }) => (
        <BoolField
          label="Has an AML risk analysis been conducted?"
          hint="Documented risk assessment of money laundering and terrorist financing exposure — §5 GwG."
          value={field.value} onChange={field.onChange}
        />
      )} />

      <Controller control={control} name="has_aml_officer" render={({ field }) => (
        <BoolField
          label="Is a designated AML compliance officer (Geldwäschebeauftragter) appointed?"
          hint="Required for regulated financial institutions and larger obligated entities — §7 GwG."
          value={field.value} onChange={field.onChange}
        />
      )} />

      <Controller control={control} name="has_kyc_procedures" render={({ field }) => (
        <BoolField
          label="Are KYC (Know Your Customer) procedures in place?"
          hint="Customer identification and verification before establishing a business relationship — §10 GwG."
          value={field.value} onChange={field.onChange}
        />
      )} />

      {/* EU Data Act */}
      <div className="pt-4 pb-1">
        <p className="text-xs font-bold uppercase tracking-widest text-brand-400">EU Data Act</p>
      </div>

      <Controller control={control} name="produces_connected_products" render={({ field }) => (
        <BoolField
          label="Does the company manufacture connected (IoT) products?"
          hint="Smart devices, industrial sensors, wearables, connected vehicles, or any product that generates data during use."
          value={field.value} onChange={field.onChange}
        />
      )} />

      <Controller control={control} name="provides_data_processing_services" render={({ field }) => (
        <BoolField
          label="Does the company provide cloud or data processing services?"
          hint="Cloud hosting, SaaS platforms, edge computing, or other data processing services with switching obligations — Art. 23-25."
          value={field.value} onChange={field.onChange}
        />
      )} />

      <Controller control={control} name="has_data_access_mechanism" render={({ field }) => (
        <BoolField
          label="Is there a mechanism for users to access their device-generated data?"
          hint="Connected product users must be able to access data generated by their devices easily — Art. 4 EU Data Act."
          value={field.value} onChange={field.onChange}
        />
      )} />
    </div>
  );
}
